export const InterlocuteurForms = [
    {
        label: "Nom",
        type: "text",
        placeholder: "Nom",
        name: "nom",
        value: "",
        select: [],
    },
    {
        label: "Prénoms",
        type: "text",
        placeholder: "Prénoms",
        name: "prenoms",
        value: "",
        select: [],
    },
    {
        label: "Email",
        type: "text",
        placeholder: "Email",
        name: "email",
        value: "",
        select: [],
    },
    {
        label: "Télephone",
        type: "text",
        placeholder: "Ex: +22402515840",
        name: "telephone",
        value: "",
        select: [],
    },
    {
        label: "Poste",
        type: "text",
        placeholder: "Email du client",
        name: "poste",
        value: "",
        select: [],
    },
];
