export const InterlocuteurForms = [
    {
        label: "Nom",
        type: "text",
        placeholder: "Nom du client",
        name: "",
        value: "",
        select: [],
    },
    {
        label: "Email",
        type: "text",
        placeholder: "Email du client",
        name: "",
        value: "",
        select: [],
    },
    {
        label: "Prenom",
        type: "text",
        placeholder: "Email du client",
        name: "",
        value: "",
        select: [],
    },
    {
        label: "Poste",
        type: "text",
        placeholder: "Email du client",
        name: "",
        value: "",
        select: [],
    },
    {
        label: "telephone",
        type: "text",
        placeholder: "Email du client",
        name: "",
        value: "",
        select: [],
    },
];
