export const StagiaireTables = [
  {
    label: 'ID',
    field: 'id',
    status: null,
    color: null,
    bgColor: null,
 },
 {
    label: 'Photos',
    field: 'image',
    status: null,
    color: null,
    bgColor: null,
 },
 {
    label: 'Nom',
    field: 'nom',
    status: null,
    color: null,
    bgColor: null,
 },
 {
    label: 'Prénoms',
    field: 'prenoms',
    status: null,
    color: null,
    bgColor: null,
 },
 {
    label: 'Email',
    field: 'email',
    status: null,
    color: null,
    bgColor: null,
 },
 {
    label: 'Téléphone',
    field: 'telephone',
    status: null,
    color: null,
    bgColor: null,
 },
 {
    label: 'Type de stage',
    field: 'type_stage',
    status: null,
    color: null,
    bgColor: null,
 },
//  {
//     label: 'Fonctions',
//     field: 'fonction',
//     status: null,
//     color: null,
//     bgColor: null,
//  },
 // {
 //    label: "Type d'Utilisateur",
 //    field: 'role',
 //    status: null,
 //    color: null,
 //    bgColor: null,
 // },
];
