export const BilanTables = [
    {
        label: 'Montant Bon de Commande Client',
        field: 'client_montant_bon_de_commande',
        status: null,
        color: null,
        bgColor: null,
    },
    {
        label: 'Montant Facture en Attente Client',
        field: 'client_montant_facture_en_attente',
        status: null,
        color: null,
        bgColor: null,
    },
    {
        label: 'Montant Facture Partiellement Payé Client',
        field: 'client_montant_facture_partiellement_paye',
        status: null,
        color: null,
        bgColor: null,
    },
    {
        label: 'Montant Facture Payé Client',
        field: 'client_montant_facture_paye',
        status: null,
        color: null,
        bgColor: null,
    },
    {
        label: 'Montant Global Facture Client',
        field: 'client_montant_globale_facture',
        status: null,
        color: null,
        bgColor: null,
    },
    {
        label: 'Montant Paiement Client',
        field: 'client_montant_paiement',
        status: null,
        color: null,
        bgColor: null,
    },
    {
        label: 'Nombre Bon de Commande Client',
        field: 'client_nombre_bon_de_commande',
        status: null,
        color: null,
        bgColor: null,
    },
    {
        label: 'Nombre Facture en Attente Client',
        field: 'client_nombre_facture_en_attente',
        status: null,
        color: null,
        bgColor: null,
    },
    {
        label: 'Nombre Facture Partiellement Payé Client',
        field: 'client_nombre_facture_partiellement_paye',
        status: null,
        color: null,
        bgColor: null,
    },
    {
        label: 'Nombre Facture Payé Client',
        field: 'client_nombre_facture_paye',
        status: null,
        color: null,
        bgColor: null,
    },
    {
        label: 'Nombre Global Facture Client',
        field: 'client_nombre_global_facture',
        status: null,
        color: null,
        bgColor: null,
    },
    {
        label: 'Nombre Paiement Client',
        field: 'client_nombre_paiement',
        status: null,
        color: null,
        bgColor: null,
    },
    {
        label: 'Montant Bon de Commande Fournisseur',
        field: 'fournisseur_montant_bon_de_commande',
        status: null,
        color: null,
        bgColor: null,
    },
    {
        label: 'Montant Facture en Attente Fournisseur',
        field: 'fournisseur_montant_facture_en_attente',
        status: null,
        color: null,
        bgColor: null,
    },
    {
        label: 'Montant Facture Partiellement Payé Fournisseur',
        field: 'fournisseur_montant_facture_partiellement_paye',
        status: null,
        color: null,
        bgColor: null,
    },
    {
        label: 'Montant Facture Payé Fournisseur',
        field: 'fournisseur_montant_facture_paye',
        status: null,
        color: null,
        bgColor: null,
    },
    {
        label: 'Montant Global Facture Fournisseur',
        field: 'fournisseur_montant_globale_facture',
        status: null,
        color: null,
        bgColor: null,
    },
    {
        label: 'Montant Paiement Fournisseur',
        field: 'fournisseur_montant_paiement',
        status: null,
        color: null,
        bgColor: null,
    },
    {
        label: 'Nombre Bon de Commande Fournisseur',
        field: 'fournisseur_nombre_bon_de_commande',
        status: null,
        color: null,
        bgColor: null,
    },
    {
        label: 'Nombre Facture en Attente Fournisseur',
        field: 'fournisseur_nombre_facture_en_attente',
        status: null,
        color: null,
        bgColor: null,
    },
    {
        label: 'Nombre Facture Partiellement Payé Fournisseur',
        field: 'fournisseur_nombre_facture_partiellement_paye',
        status: null,
        color: null,
        bgColor: null,
    },
    {
        label: 'Nombre Facture Payé Fournisseur',
        field: 'fournisseur_nombre_facture_paye',
        status: null,
        color: null,
        bgColor: null,
    },
    {
        label: 'Nombre Global Facture Fournisseur',
        field: 'fournisseur_nombre_global_facture',
        status: null,
        color: null,
        bgColor: null,
    },
    {
        label: 'Nombre Paiement Fournisseur',
        field: 'fournisseur_nombre_paiement',
        status: null,
        color: null,
        bgColor: null,
    },
    {
        label: 'Montant Dépense Banque',
        field: 'montant_depense_banque',
        status: null,
        color: null,
        bgColor: null,
    },
    {
        label: 'Montant Dépense Caisse',
        field: 'montant_depense_caisse',
        status: null,
        color: null,
        bgColor: null,
    },
    {
        label: 'Montant Entrée Banque',
        field: 'montant_entree_banque',
        status: null,
        color: null,
        bgColor: null,
    },
    {
        label: 'Montant Entrée Caisse',
        field: 'montant_entree_caisse',
        status: null,
        color: null,
        bgColor: null,
    },
    {
        label: 'Montant Produit',
        field: 'montant_produit',
        status: null,
        color: null,
        bgColor: null,
    },
    {
        label: 'Montant Service',
        field: 'montant_service',
        status: null,
        color: null,
        bgColor: null,
    },
    {
        label: 'Nombre Client',
        field: 'nombre_client',
        status: null,
        color: null,
        bgColor: null,
    },
    {
        label: 'Nombre Dépense Banque',
        field: 'nombre_depense_banque',
        status: null,
        color: null,
        bgColor: null,
    },
    {
        label: 'Nombre Dépense Caisse',
        field: 'nombre_depense_caisse',
        status: null,
        color: null,
        bgColor: null,
    },
    {
        label: 'Nombre Entrée Banque',
        field: 'nombre_entree_banque',
        status: null,
        color: null,
        bgColor: null,
    },
    {
        label: 'Nombre Entrée Caisse',
        field: 'nombre_entree_caisse',
        status: null,
        color: null,
        bgColor: null,
    },
    {
        label: 'Nombre Fournisseur',
        field: 'nombre_fournisseur',
        status: null,
        color: null,
        bgColor: null,
    },
    {
        label: 'Nombre Produit',
        field: 'nombre_produit',
        status: null,
        color: null,
        bgColor: null,
    },
    {
        label: 'Nombre Prospect',
        field: 'nombre_prospect',
        status: null,
        color: null,
        bgColor: null,
    },
    {
        label: 'Nombre Service',
        field: 'nombre_service',
        status: null,
        color: null,
        bgColor: null,
    },
]