export const CongeTables = [
    {
        label: 'ID',
        field: 'id',
        status: null,
        color: null,
        bgColor: null,
    },
    {
        label: 'EMPLOYE',
        field: 'employe',
        status: null,
        color: null,
        bgColor: null,
    },
    {
        label: 'Type',
        field: 'type',
        status: null,
        color: null,
        bgColor: null,
    },
    {
        label: 'MOTIF',
        field: 'motif',
        status: null,
        color: null,
        bgColor: null,
    },
    {
        label: 'DATE DE DEPART',
        field: 'date_depart',
        status: null,
        color: null,
        bgColor: null,
    },
    {
        label: 'DATE DE RETOUR',
        field: 'date_retour',
        status: null,
        color: null,
        bgColor: null,
    },
    {
        label: 'NOMBRE DE JOURS',
        field: 'nbr_jours',
        status: null,
        color: null,
        bgColor: null,
    },
    {
        label: 'SOLDE CONGE ANNUEL',
        field: 'solde_conge_annuel',
        status: null,
        color: null,
        bgColor: null,
    },
    {
        label: 'REMARQUES',
        field: 'remarque',
        status: null,
        color: null,
        bgColor: null,
    },
]