export const PartnerTables = [
    {
       label: 'Nom',
       field: 'nom',
       status: null,
       color: null,
       bgColor: null,
    },
    {
       label: 'Email',
       field: 'email',
       status: null,
       color: null,
       bgColor: null,
    },
    {
       label: 'Téléphone',
       field: 'telephone',
       status: null,
       color: null,
       bgColor: null,
    },
    {
       label: 'Adresse',
       field: 'adresse',
       status: null,
       color: null,
       bgColor: null,
    },
    // {
    //    label: 'Nom Interlocuteur',
    //    field: 'nom_interlocuteur',
    //    status: null,
    //    color: null,
    //    bgColor: null,
    // },
    // {
    //    label: 'Proposition',
    //    field: 'proposition',
    //    status: null,
    //    color: null,
    //    bgColor: null,
    // },
    // {
    //    label: 'Étape',
    //    field: 'etape',
    //    status: null,
    //    color: null,
    //    bgColor: null,
    // },
    // {
    //    label: 'Observation',
    //    field: 'observation',
    //    status: null,
    //    color: null,
    //    bgColor: null,
    // },
];
