export const ProductForms = [
  {
    label: "Libelle",
    type: "text",
    placeholder: "Libelle",
    name: "libelle",
    value: "",
    select: [],
  },
  {
    label: "Reference",
    type: "number",
    placeholder: "Ex: Unil",
    name: "Reference",
    value: "",
    select: [],
  },
  {
    label: "Description",
    type: "text",
    placeholder: "Ex: Unil",
    name: "description",
    value: "",
    select: [],
  },
  {
    label: "Type",
    type: "text",
    placeholder: "Type",
    name: "type",
    value: "",
    select: [
      {
        id: "produit",
        label: "Produit",
      },
      {
        id: "service",
        label: "Service",
      },
    ],
  },
  {
    label: "Marque",
    type: "text",
    placeholder: "Marque",
    name: "marque",
    value: "",
    select: [],
  },
  {
    label: "Image",
    type: "file",
    placeholder: "Ajoutez une image",
    name: "image",
    value: "",
    select: [],
  },
  {
    label: "Prix unitaire",
    type: "number",
    placeholder: "Ex: 50.000",
    name: "prix_unitaire",
    value: "",
    select: [],
  },
  {
    label: "Unité",
    type: "text",
    placeholder: "Ex: Unil",
    name: "unite",
    value: "",
    select: [],
  },

  {
    label: "Devise",
    type: "text",
    placeholder: "Ex: Unil",
    name: "reference",
    value: "",
    select: [],
  },
];
